name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # هر روز راس 00:00 UTC اجرا میشه
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake
        uses: Platane/snk@master
        with:
          github_user_name: fatemeh-shahrabi
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
